spring.application.name=prueba-back-end

# Conexion R2DBC con MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3306/franchise_db
spring.r2dbc.username=root
spring.r2dbc.password=root

# Inicializacion automatica del schema
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
